name: witibju
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

  # 공통
  cupertino_icons: ^1.0.8 #iOS 스타일 아이콘 제공
  provider: ^6.0.0 # Flutter에서 상태 관리를 쉽게 할 수 있도록 도와주는 패키지
  image_picker: ^0.8.4+3 #flutter에서 사진 및 동영상을 선택하거나 찍을 수 있도록 도와주는 패키지
  fluttertoast: ^8.2.2  #토스트 메시지(화면에 잠깐 동안 나타났다 사라지는 짧은 알림 메시지)
  image: ^3.0.1 #위젯으로, 애플리케이션에서 이미지 표시
  multi_select_flutter: ^4.1.3 #멀티 셀렉트 드롭다운 및 목록

  #통신
  http: ^0.13.4 #HTTP 요청을 처리하기 위한 패키지
  get: ^4.6.0 # REST API 호출

  #카카오
  kakao_flutter_sdk_user: ^1.9.5 # 카카오 로그인 API 패키지

  flutter_secure_storage: ^8.0.0 # Session
  #채팅
  uuid: ^3.0.7 #고유한 식별자를 생성 채팅의 키생성등
  stomp_dart_client: ^2.0.0 # 채팅 WebSocket 클라이언트 라이브러리
  flutter_chat_types: ^3.6.2 #채팅 애플리케이션을 개발할 때 사용되는 데이터 모델과 타입
  flutter_chat_ui: ^1.6.15 #채팅 애플리케이션 UI

  #토스결재 위젯
  #tosspayments_widget_sdk_flutter: 2.0.0
  #우편번호
  kpostal: ^1.0.0

  #웹소켓
  web_socket_channel: ^2.1.0
  timezone: ^0.9.4
  # 푸쉬알림
  flutter_local_notifications: ^18.0.1
  # 권한 핸들러
  permission_handler: ^11.3.1



dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/
    - assets/home/
    - assets/chat/
    - assets/seller/
    - assets/chat/messages.json
  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf
        - asset: assets/fonts/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/WorkSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/WorkSans-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 400

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
